<!DOCTYPE html >
<html lang= "es" >
<head>
	<title>Evaluacion</title>
    <meta charset = "utf-8" />
    <meta name="description" content="Bienvenido" />
    <meta name = "viewport" content ="width= devide-with, inicial-scale=1" />
    <link rel="shortcut icon" type="image/x-icon" href= "" />
    <link rel="author" type="text/plain" href= "humans.txt" />
    <link rel="sitemap" type="application/xml" title="Sitemap" href= "sitemap.xml" />
    
   
 	
    <link rel="stylesheet" href= "./public/css/estilos.css" />
    
 
	<script type="text/javascript" src="./public/js/jquery/jquery.1.8.1.js"></script>
	<script type="text/javascript" src="./public/js/jquery_ui/jquery-ui-1.8.23.custom.min.js"></script>
    
    
	<script language="javascript" type="text/javascript" src="./public/js/funciones.js"></script>
  

</head>

<body>
    <header>
        <!--  START HEADER -->
        <div id="header">
            <!--  START HEAD_WRAP -->
            <?php include("header.phtml");?>
            <!--  END HEAD_WRAP -->
        </div><!--  end div #header -->
        <!--  END HEADER -->   
    </header>
    
    <section id="contenido">
        <section id="principal">
            <article id="Info">
                <!--  START CONTENT WRAPPER -->
                <div id="content_wrapper">
                    <!--  START PRIMARY CONTENT -->
                    <div id="primary_content">
                        
                        <h2>Sistema para evaluar la salud de su empresa.</h2>
                        <p>Debe seguir con los pasos indicados a continuación para que le entreguemos una evaluación de su empresa.</p>
                        
                        
                        <!--<div class="information large png_bg">For the demo, just hit the login button</div>-->
                        
                        <form action="" method="post" name="form">
                        	<fieldset>
                        		<legend>Ejecutar estos pasos:</legend>
	                        	<table>
			                          <tr>
			                          	<td valign="top" align="left">
			                            	<label for="bajarplantilla">1. Descargue esta plantilla y llene con los datos de su empresa:</label>
			                          	</td>
                                        <td valign="middle" align="left">
                                            <div id="btnbajarplantillas"><a href="javascript:void(0);" data-accion="bajarplantillas" title="Descargar Plantilla" ><img src="public/images/save_download_32.png" border="0" width="24" height="24" /></a></div>
                                        </td>     
			        				  </tr>

			        				  <tr></tr>
			        				  <tr></tr>

			        				  <tr>
			                            <td valign="top" align="left">
			                            	<label for="password">2. Escoja el archivo que llenó y presione el boton subir archivo:</label>
			                           	</td>
                                        <td valign="middle" align="left">
                                            <div id="btnGuardarRendArch"><a href="javascript:void(0);" data-accion="guardarrendarch" title="Subir Archivo" ><img src="public/images/save_upload_32.png" border="0" width="24" height="24" /></a></div>
                                        </td>    
			                            <td valign="top" align="left">
                                            <input name="subirarchivo" type="file" class="fade" id="subirarchivo" value="" onblur="" />
			                           	</td>
                                        
			                          </tr>

                                      <tr></tr>
			        				  <tr></tr>

                                      <tr>
			                            <td valign="top" align="left">
			                            	<label for="generarpdf">3. Presione el boton para generar la evaluación en un archivo pdf:</label>
			                           	</td>
                                        <td valign="middle" align="left">
                                            <div id="btngenerarpdf"><a href="javascript:void(0);" data-accion="descargarrendarch" title="Descargar Evaluacion" ><img src="public/images/save_download_32.png" border="0" width="24" height="24" /></a></div>
                                        </td>
			                          </tr>

			                          <tr>
			                          	<td valign="top" align="left">
			                            	<input type="hidden" id="sufijoarchivo" value="" />
			                            	<p><div id="valor"></div></p>	
			                          	</td>
			                          </tr>
	                        	</table>
                        	</fieldset>
                        </form>    
                        
                        <?php
                        //echo 'Archivo pdf creado.';
                        //require_once("./model/archivopdfModel.php");


                                
                        //$emp=new Generacion();
                        //$emp->generarpdf();



                        ?>
                        
                    </div>
                    <!--  END PRIMARY CONTENT -->   
                      
                </div><!--  end div #content_wrapper -->
                <!--  END CONTENT_WRAPPER -->
        	</article>

            

        </section>
        
        <aside>
        	<!--  START SIDEBAR -->
            <?php include("sidebar.phtml");?>
            <!--  end div #sidebar -->
            <!--  END SIDEBAR -->
        
        </aside>
        
        
    </section>
    
    <footer>
        <!--  START FOOTER -->
        <div id="footer">
            <p>
            <?php include("footer.phtml");?>
            </p>
        </div>
        <!--  END CEND -->
    </footer>
</body>
</html>