<!DOCTYPE html >
<html lang= "es" >
<head>
	<title>..:: Log in ::..</title>
    <meta charset = "utf-8" />
    <meta name="description" content="Bienvenido" />
    <meta name = "viewport" content ="width= devide-with, inicial-scale=1" />
    <link rel="shortcut icon" type="image/x-icon" href= "public/images/favicon.ico" />
    <link rel="author" type="text/plain" href= "humans.txt" />
    <link rel="sitemap" type="application/xml" title="Sitemap" href= "sitemap.xml" />
    
    <link href="public/css/smoothness/jquery-ui-1.8.23.custom.css" rel="stylesheet" media="screen">
 	
    <link rel="stylesheet" href= "public/css/estilos.css" />
    
 
	<script type="text/javascript" src="public/js/jquery/jquery.1.8.1.js"></script>
	<script type="text/javascript" src="public/js/jquery_ui/jquery-ui-1.8.23.custom.min.js"></script>
    
    
	<script language="javascript" type="text/javascript" src="public/js/funciones.js"></script>
  

</head>

<body>
    <header>
        <!--  START HEADER -->
        <div id="header">
            <!--  START HEAD_WRAP -->
            <?php include("header.phtml");?>
            <!--  END HEAD_WRAP -->
        </div><!--  end div #header -->
        <!--  END HEADER -->   
    </header>
    
    <section id="contenido">
        <section id="principal">
            <article id="Info">
                <!--  START CONTENT WRAPPER -->
                <div id="content_wrapper">
                    <!--  START PRIMARY CONTENT -->
                    <div id="primary_content">
                        
                        <h2>Sistema para evaluar la salud de su empresa.</h2>
                        <p>Debe seguir con los pasos indicados a continuación para que le entreguemos una evaluación de su empresa.</p>
                        
                        
                        <!--<div class="information large png_bg">For the demo, just hit the login button</div>-->
                        
                        <form action="" method="post" name="form">
                        	<fieldset>
                        		<legend>Ejecutar estos pasos:</legend>
	                        	<table>
			                          <tr>
			                          	<td valign="top" align="left">
			                            	<label for="login">1. Descargar esta plantilla y llenar con los datos de su empresa:</label>
			                          	</td>
			                          	<td valign="top" align="left">
			                            	<input name="login" type="text" class="fade" id="login" value="" required />
			                           	</td>     
			        				  </tr>

			        				  <tr></tr>
			        				  <tr></tr>

			        				  <tr>
			                            <td valign="top" align="left">
			                            	<label for="password">2. Subir la plantilla con los datos de su empresa:</label>
			                           	</td>
			                            <td valign="top" align="left">
			                            	<input name="pass" type="text" class="fade" id="pass" value="" required />
			                           	</td>
			                          </tr>

                                      <tr>
			                            <td valign="top" align="left">
			                            	<label for="password">3. Generar la evaluación en archivo pdf:</label>
			                           	</td>
			                            <td valign="top" align="left">
			                            	<input name="pass" type="text" class="fade" id="pass" value="" required />
			                           	</td>
			                          </tr>

			                          <tr></tr>
			                          <tr></tr>

			                          <tr>
			                          	<td valign="top" align="left">
			                            	<input type="button" value="Entrar"  class="button" onclick="valida_logueo()"/>
			                          	</td>
			                          	<td valign="top" align="left">
			                            	<input type="button"  value="Limpiar" class="button" onclick="window.location='';" />
			                           	</td>      	
			                          </tr>

			                          <tr>
			                          	<td valign="top" align="left">
			                            	<input type="hidden" name="grabar" value="si" />
			                            	<p><div id="valor"></div></p>	
			                          	</td>
			                          </tr>
	                        	</table>
                        	</fieldset>
                        </form>    
                        
                        
                    </div>
                    <!--  END PRIMARY CONTENT -->   
                      
                </div><!--  end div #content_wrapper -->
                <!--  END CONTENT_WRAPPER -->
        	</article>

            <?php include("model/archivopdfModel.php");?>

        </section>
        
        <aside>
        	<!--  START SIDEBAR -->
            <?php include("sidebar.phtml");?>
            <!--  end div #sidebar -->
            <!--  END SIDEBAR -->
        
        </aside>
        
        
    </section>
    
    <footer>
        <!--  START FOOTER -->
        <div id="footer">
            <p>
            <?php include("footer.phtml");?>
            </p>
        </div>
        <!--  END CEND -->
    </footer>
</body>
</html>