<article id="info-contacto">
	<p>
        Email:<br />
        <span class="datos-contacto">jrmunozv@yahoo.com</span>
        <br />

        M&oacute;vil:<br />
        <span class="datos-contacto">56+990184821</span>
        <br />

        Web:<br />
        <span class="datos-contacto">Definir</span>
        <br />
        
        Direccion:<br />
        <span class="datos-contacto">Osorno</span>
        <br />
        
        Social Media:<br />
        <span class="datos-contacto">
            <a class="fade" href="http://facebook.com" title="Facebook"><img src="public/images/facebook-logo.png" /></a>
            &nbsp;&nbsp;&nbsp;

            <a class="fade" href="http://twitter.com" title="Twitter"><img src="public/images/twitter-logo.png" /></a>
            &nbsp;&nbsp;&nbsp;

            <a class="fade" href="http://plus.google.com/u/0/113763991432440801400/" title="Google +"><img src="public/images/google-plus-logo.png" /></a>
            &nbsp;&nbsp;&nbsp;

            <a class="fade" href="http://youtube.com" title="Youtube"><img src="public/images/youtube-logo.png" /></a>
            &nbsp;&nbsp;&nbsp;
        </span>
    </p>
</article>